### ISSUE TITLE
Append metadata title during encoding

### ISSUE THREAD

**Issue by leewdch** [ElegantMonkey/mpv-webm#20] opened 2018-05-13 14:45 UTC
Here is a suggestion: an option (toggled on by default if possible) that copies the filename and uses it during the video encoding to add a metadata title. This is useful for those video that lost the original name title. Thanks to this you can track down the origin of a file even after multiple encoding since the metadata title should be preserved even after additional encodings with ffmpeg. Right now I have to do this with a bash script like this:

```
filename=$(basename -- "$i")
tempname=${filename%.*}_tmp.${filename##*.}

mv "$filename" "$tempname"
ffmpeg -i "$tempname" -c copy -metadata title="$filename" "$filename"
rm "$tempname"
```

but I would rather do the job during video encoding so I don't need to make and remove useless temp files

**Comment by ElegantMonkey** [comment] 2018-05-15 19:40
Duplicate of #12, although he closed the issue when he wrote his own code for that.

I still kinda doubt the usefulness of this, but I'll do it anyway. Soon(tm).

**Comment by leewdch** [comment] 2018-05-15 19:46
Thanks. Now that I'm thinking about it this shoukd be set off by default or it will affect other people who dont want to edit their metadata at all

**Closed** 2018-05-15 19:58 UTC

**Comment by leewdch** [comment] 2018-05-16 16:16
I tried the script but the encode fails and it asks me to check the logs. I didn't find logs in my home, source directory or in my mpv config directory

**Comment by ElegantMonkey** [comment] 2018-05-16 18:12
Please run mpv in the console with the `-v` and post the output, or add the `log-file=log.txt` line to your mpv.conf and upload the resulting `log.txt` file (it will be in the same directory as the video file you're watching).

**Comment by ElegantMonkey** [comment] 2018-05-17 12:37
I need that you try to encode something and  trigger the error, so that I can examine the logs.

**Comment by leewdch** [comment] 2018-05-17 12:48
[log.zip](https://github.com/ElegantMonkey/mpv-webm/files/2013171/log.zip)

**Comment by ElegantMonkey** [comment] 2018-05-17 13:11
```
[  20.924][v][webm] Error parsing option oset-metadata (option not found)
[  20.924][v][webm] Setting commandline option --oset-metadata=title=%42%[HorribleSubs] Fumikiri Jikan - 05 [1080p] failed.
```

Is your mpv updated? This was added quite some time ago.

**Comment by leewdch** [comment] 2018-05-17 13:28
switching from mpv to mpv-git in the AUR fixed the issue
